### ISSUE TITLE
Queues don't scroll.

### ISSUE THREAD

**Issue by SixFive7** [VoIPGRID/chrome-extension#23]
On chrome 49.0.2623.112 m (64-bit) only the first 10 queues are shown. If you open availability or colleagues even less are shown. The colleagues list does have a scroll bar however so it's not a global problem.

**Comment by cpoppema** [comment]
Helllo @SixFive7,

I was able to confirm that at most 10 queues are visible. I will be following up on this in the next 2-4 weeks.

**Comment by bobvoorneveld** [comment]
Hello @SixFive7,

I've fixed the problem. The new version of the extension should be in the store in the next 24 hours. Thanks for your feedback!
