### ISSUE TITLE
repository status? Vialer?

### ISSUE THREAD

**Issue by slokhorst** [VoIPGRID/chrome-extension#26]
It looks like you are currently offering a "Vialer" extension on the [Chrome Web Store](https://chrome.google.com/webstore/detail/vialer/eadmnmeebenjobnopaaoemfoafpimdhg), which seems to be based on this extension but has been updated more recently and is at version 2.2.1, while this repository is stuck at version 1.4.10.

Have you gone closed-source with the plugin and is this repository no longer used? Is the Vialer source code available somewhere else?

**Comment by slokhorst** [comment]
Looks like https://github.com/vialer/vialer-js is related (based on [this post](https://www.voipgrid.nl/blog/vialer-plugin-chrome-en-firefox/)), but that's discontinued as well?

**Comment by slokhorst** [comment]
Aha, found it: https://github.com/vialer/vialer-clicktodial

Maybe mention this somewhere in the readme?

**Comment by m-vellinga** [comment]
You are right, this repo and it's firefox counterpart are from a day and age where you could not use the same codebase for both browsers. This code is obsolete and the repository is no longer relevant. I'll accept your pull request until we have decided what to do with this repository. Thanks for pointing it out!
